[project]
name = "audio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "google-api-python-client>=2.188.0",
    "jupyter>=1.1.1",
    "notebook>=7.5.3",
    "openai-whisper>=20250625",
    "youtube-transcript-api>=1.2.4",
    "yt-dlp>=2026.1.31",
]
